defaults: &defaults
  adapter: postgresql

development:
  <<: *defaults
  database: everyday_hero_hub_development

test:
  <<: *defaults
  database: everyday_hero_hub_test

production:
  <<: *defaults
  database: everyday_hero_hub_production
